#! -*- coding: utf-8 -*-

# Description    NAMASTOX command
#
# Authors:       Manuel Pastor (manuel.pastor@upf.edu)
#
# Copyright 2022 Manuel Pastor
#
# This file is part of NAMASTOX
#
# NAMASTOX is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation version 3.
#
# Flame is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NAMASTOX. If not, see <http://www.gnu.org/licenses/>.

import pickle
import numpy as np
import json
import yaml
import os

class NAM:
    def __init__(self, name, description=None):
        self.name = name
        self.decription = description

class substance:
    def __init__(self, name, ID, CASRN=None, SMILES=None):
        self.name = name
        self.ID = ID
        self.CASRN=CASRN
        self.SMILES=SMILES

class endpoint:
    def __init__(self, name, description=None):
        self.name = name
        self.decription = description

class ra:
    ''' Class storing all the risk assessment information
    '''
    def __init__(self):
        ''' constructor '''
        self.ID = {}
        self.results = {}
        self.NAMS = []
        self.substances = []
        self.endpoints = []
        self.error = None
        self.warning = None

    def loadYaml(self, raname, version):       
        ''' load the ra object from a YAML file

        '''
        # obtain the path and the default name of the raname parameters
        ra_file_path = utils.ra_path(raname, version)
        
        if not os.path.isdir (ra_file_path):
            return False, f'RA "{raname}", version "{version}" not found'

        ra_file_name = os.path.join (ra_file_path,'ra.yaml')

        # load the main class dictionary (p) from this yaml file
        if not os.path.isfile(ra_file_name):
            return False, 'Parameters file not found'

        try:
            with open(ra_file_name, 'r') as pfile:
                self.p = yaml.safe_load(pfile)
        except Exception as e:
            return False, e

        # add keys for the raname and a MD5 hash
        self.setVal('raname',raname)
        self.setVal('version',version)
        self.setVal('rapath',ra_file_path)
        self.setVal('md5',self.idataHash())

        return True, 'OK'

    def applyDelta (self, newp):
        # update interna dict with keys in the input file (delta)
        black_list = ['raname', 'version', 'rapath', 'md5']
        for key in newp:
            if key not in black_list:

                val = newp[key]

                # YAML define null values as 'None, which are interpreted 
                # as strings
                if val == 'None':
                    val = None

                if isinstance(val ,dict):
                    for inner_key in val:
                        inner_val = val[inner_key]

                        if inner_val == 'None':
                            inner_val = None

                        self.setInnerVal(key, inner_key, inner_val)
                        #print ('@delta: adding',key, inner_key, inner_val)
                else:
                    self.setVal(key,val)


    def delta(self, raname, version, param):
        ''' load a set of parameters from the configuration file present 
            at the raname directory

            also, inserts the keys present in the param_file provided, 
            assuming that it contains a YAML-compatible format, like the one
            generated by manage

            adds some parameters identifying the raname and the 
            hash of the configuration file 
        '''

        if not self.loadYaml (raname, version):
            return False, 'file not found'
        
        # parse parameter file 

        newp = json.load(pfile)
        self.applyDelta(newp)
        ra_file_path = utils.raname_path(raname, version)
        ra_file_name = os.path.join (ra_file_path,'ra.yaml')
        try:
            with open(ra_file_name, 'w') as pfile:
                yaml.dump (self.p, pfile)
        except Exception as e:
            return False, 'unable to write parameters'

        # self.setVal('md5',utils.md5sum(ra_file_name))
        self.setVal('md5',self.idataHash())

        return True, 'OK'

    def load (self):
        print ('load')

    def save (self):
        print ('save')

    def getJSON (self):
        print ('getJSON')
        temp_json = {}
        temp_json['ID']=self.ID
        temp_json['results']=self.results
        temp_json['NAMS']=self.NAMS
        temp_json['substances']=self.substances
        temp_json['endpoints']=self.endpoints
        return json.dumps(temp_json, allow_nan=True)

